### ISSUE TITLE
Championing Individual Member Outside GitHub and Outreach

### ISSUE THREAD

**Issue by codeekage** [nodejs/outreach#1]
I think Node.js has grown beyond the point of just its GitHub Org and we as it contributors and collaborators should be able to carry the community and ecosystem out to the general public. 

It's quite interesting that Node.js developers around the globe have been able to put together events that bring the community together... but as collaborators to the community and the top-level administration (CommComm) to the Node.js GitHub Org, whereas we are the representative of the underrepresented groups in the Node.js ecosystem, we should also be able to represent these groups at foundation level, making them feel part of what we do in administration and not being exclusive to github (which is more of collaboration at code, even if we've succeeded to use this medium for community collaboration and administration). 

I think having a champion or a director to organize and manage communities, that will be recognized as official Node.js Foundation Communities outside GitHub and its individual members who are not neccesarily collaborators to the TSC/CommComm is the beginning of inclusivity and diversity in the Node.js Project.

I nominate myself to champion and direct this initiative, as I have been able to reach out to Node.js Africa as a medium of having an official Node.js community in Africa. I know if given an oppurtunity to represent Individual members at Foundation level, I will be able to carrying out the task of setting up official Node.js Communities around the globe with the support of both the TSC/CommComm and every member of the Node.js GitHub Org.

Thank you 🙏 .

**Comment by patriciarealini** [comment]
Hi Agiri, 

Wow! Your enthusiasm for this initiative and your passion for helping raise the voices of the underrepresented is invigorating! I want to assume based on your zeal that you were able to catch the livestream of our discussions at the Node Collaborator Summit in Berlin last week. If not I would be more than happy to fill you in on the establishment of this project. 

Because this initiative is about ALL underrepresented people in Node.js we feel it is important that the initiative reflect that and therefore it will be run by a committee of co-chairs and not by an individual champion. But please do not let that hamper your keenness for being a part of this work. At this time, the initiative is only just forming and I would love to chat with you more. I personally think there is a place for you as a co-chair (though i know there have been some miscommunications). If you are still interested please let us know! And feel free to reach out to me anytime, my email is hello@patriciarealini.com.

🌺Patricia Realini
https://patriciarealini.com
